SET(XML2_FOUND TRUE)
SET(XML2_INCLUDE_DIRS /usr/include/libxml2/ )
SET(XML2_LIBRARY_DIRS /usr/lib/x86_64-linux-gnu/)
SET(XML2_LIBRARIES  @XML2_LIBRARIES_DEP@ )

SET(XML2_LIBRARIES_LIST   xml2)

FOREACH (LIB_ ${XML2_LIBRARIES_LIST})
    find_library(${LIB_}_FILE NAMES ${LIB_} PATHS ${XML2_LIBRARY_DIRS})
    IF (NOT ${LIB_}_FILE-NOTFOUND)
        LIST(APPEND XML2_LIBRARIES ${${LIB_}_FILE})
    ENDIF (NOT ${LIB_}_FILE-NOTFOUND)
ENDFOREACH (LIB_ ${XML2_LIBRARIES_LIST})