@startuml
class DataEntry{
    DataTable attributes
    DataEntry sub[]
}

class DataTable{
    map<std::string,DataEntity> m_values_
}
class DataEntity{
}
DataEntry *-- DataTable
DataTable *-- DataEntity
DataEntry *-- DataEntry
@enduml